browser=chrome
headless=false
chrome.profile.path=.naukri-chrome-profile
resume.path=C:/Users/Pratham/Downloads/NaukriResumeUpdate/Pratham_Mallick.pdf

job.type=job
job.keywords=Quality Assurance, QA, Selenium, SDET, Quality Analyst, Test Engineer, Automation Tester
job.locations=Mumbai, Navi Mumbai, Pune, Bangalore, Hyderabad, Chennai, Delhi, Gurgaon, Noida